#Vectorisation et modelisation

In [26]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

from wordcloud import WordCloud

import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
import nltk
from nltk.corpus import stopwords
from nltk.corpus import wordnet
#import contractions


nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [27]:
DATASET_FILE = "dataset_cleaned.csv"

In [28]:
dataset_df = pd.read_csv(DATASET_FILE)
dataset_df

text  stars  length  \
0      I've only had food from here once and it wasn'...      1      68   
1      I will never return here again.  Ever.  I was ...      1      87   
2      I wish my experience was great as others. I di...      1     166   
3      Are the rosemary grapefruit scones supposed to...      1      81   
4      Our takeout order was half wrong. Food was mis...      1      32   
...                                                  ...    ...     ...   
24995  I was a loyal fan of Aroy before the ownership...      5      75   
24996  Stopped here for a bite while wandering around...      5      55   
24997  A quiet place with excellent food, great music...      5      32   
24998  Super delicious food. Awesome vibe. I suffered...      5      41   
24999  I have a lot of dietary restrictions and this ...      5      87   

                                            text_cleaned  
0      food memorable panang curry balance flavor lik...  
1      NOT_return ever sit booth wait dinner come scu...  
2      wish experience great others din wednesday nig...  
3      rosemary grapefruit scone suppose taste like w...  
4      takeout order half wrong food miss portion siz...  
...                                                  ...  
24995  loyal fan aroy ownership change apprehensive v...  
24996  stopped bite wander around faneuil hall pleasa...  
24997  quiet place excellent food great music helpful...  
24998  super delicious food awesome vibe suffer disne...  
24999  lot dietary restriction place spot superfood s...  

[25000 rows x 4 columns]

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range = (1,1), max_df = .75, min_df = .01) #un seuil minimale d'apparition de mots et maximale aussi
df = dataset_df[dataset_df.stars<3]


In [30]:
X = vectorizer.fit_transform(df.text_cleaned)
feature_names = vectorizer.get_feature_names()
#create a dense list
print(X.shape)
#print(df)

(10000, 868)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [31]:
X = TfidfVectorizer(ngram_range = (1,1), max_df = .7, min_df = .01)

data_doc_mx = X.fit_transform(df.text_cleaned)

data_dtm_text = pd.DataFrame(data_doc_mx.toarray(), columns=X.get_feature_names() )

data_dtm_text.index = df.index
#dataframe tf-idf
#data_dtm_text
# print(data_doc_mx)
print(X)



TfidfVectorizer(max_df=0.7, min_df=0.01)


In [32]:
### desplay les topic functions
def display_topics(model, feature_names, num_top_words,topic_names=None):
    # iterate through topics in topic-term matrix, 'H' aka
    # model.components_
    for ix, topic in enumerate(model.components_):
        #print topic, topic number, and top words
        if not topic_names or not topic_names[ix]:
            print("\nTopic ", ix)
        else:
            print("\nTopic: '",topic_names[ix],"'")
        print(", ".join([feature_names[i] \
             for i in topic.argsort()[:-num_top_words - 1:-1]]))

In [33]:
#run modeling on doc
nmf_model = NMF(15)
# Learn an NMF model for given Document Term Matrix 'V' 
# Extract the document-topic matrix 'W'
doc_topic = nmf_model.fit_transform(data_dtm_text)
# Extract top words from the topic-term matrix 'H' display_topics(nmf_model, tv_noun.get_feature_names(), 5)
display_topics(nmf_model, X.get_feature_names(), 5)
print(doc_topic)
#print(nmf_model)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,



Topic  0
say, tell, customer, would, call

Topic  1
place, like, really, get, look

Topic  2
pizza, crust, cheese, topping, slice

Topic  3
order, take, delivery, get, wrong

Topic  4
food, service, bad, slow, terrible

Topic  5
table, come, server, waitress, ask

Topic  6
burger, fry, bun, onion, cheese

Topic  7
wait, minute, hour, 30, 15

Topic  8
chicken, rice, sauce, taste, fry

Topic  9
bar, drink, beer, bartender, night

Topic  10
time, go, last, first, location

Topic  11
taco, fish, salsa, chip, mexican

Topic  12
sandwich, salad, cheese, bread, lettuce

Topic  13
sushi, roll, fish, rice, salmon

Topic  14
good, price, dish, restaurant, menu
[[0.         0.03984389 0.         ... 0.         0.         0.04364116]
 [0.02800226 0.         0.         ... 0.00353904 0.         0.        ]
 [0.01367091 0.         0.         ... 0.         0.00717008 0.02714748]
 ...
 [0.03076499 0.         0.         ... 0.         0.         0.02351259]
 [0.         0.         0.00966072 ... 0.05

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [34]:
print(X.get_feature_names())

['00', '10', '100', '11', '12', '15', '18', '20', '25', '30', '40', '45', '50', 'able', 'absolutely', 'acknowledge', 'across', 'act', 'actual', 'actually', 'add', 'afternoon', 'ago', 'agree', 'ahead', 'allow', 'almost', 'alone', 'along', 'already', 'alright', 'also', 'although', 'always', 'amaze', 'amazing', 'ambiance', 'amount', 'annoy', 'another', 'answer', 'anymore', 'anyone', 'anything', 'anyway', 'anywhere', 'apologize', 'apparently', 'appear', 'appetizer', 'appreciate', 'area', 'around', 'arrive', 'asian', 'ask', 'assume', 'atmosphere', 'attempt', 'attention', 'attentive', 'attitude', 'austin', 'available', 'average', 'avoid', 'away', 'awesome', 'awful', 'back', 'bacon', 'bad', 'bag', 'bar', 'bartender', 'base', 'basic', 'basically', 'bathroom', 'bbq', 'bean', 'beautiful', 'become', 'beef', 'beer', 'begin', 'behind', 'believe', 'best', 'beyond', 'big', 'bill', 'birthday', 'bit', 'bite', 'black', 'bland', 'block', 'booth', 'boston', 'bother', 'bottle', 'bottom', 'bowl', 'box', 'bo

In [35]:
import pandas
liste=[]
for i in range(15):
  var='topic_'+str(i)
  liste.append(var)
liste
df_topic = pandas.DataFrame(doc_topic, columns=liste)
df_topic

topic_0   topic_1   topic_2   topic_3   topic_4   topic_5   topic_6  \
0     0.000000  0.039844  0.000000  0.000000  0.032004  0.000000  0.003098   
1     0.028002  0.000000  0.000000  0.000000  0.000000  0.024570  0.000000   
2     0.013671  0.000000  0.000000  0.002831  0.014939  0.026248  0.000000   
3     0.001464  0.044139  0.001226  0.000000  0.000000  0.019116  0.002559   
4     0.000000  0.023330  0.000000  0.052325  0.014653  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.000000  0.000000  0.001032  0.003726  0.000000  0.000000  0.000639   
9996  0.015253  0.044071  0.063700  0.008362  0.000000  0.001650  0.002486   
9997  0.030765  0.000000  0.000000  0.035115  0.015816  0.036819  0.000000   
9998  0.000000  0.000000  0.009661  0.000000  0.013545  0.000000  0.000000   
9999  0.000000  0.000000  0.000000  0.001814  0.012998  0.042453  0.000000   

      topic_7   topic_8   topic_9  topic_10  topic_11  topic_12  topic_13  \
0     0.00000  0.018250  0.000000  0.000000  0.000000  0.000000  0.000000   
1     0.02535  0.000000  0.004019  0.000000  0.001371  0.003539  0.000000   
2     0.00000  0.054742  0.026156  0.007471  0.002094  0.000000  0.007170   
3     0.00000  0.006641  0.006808  0.011468  0.000868  0.003016  0.000000   
4     0.01714  0.000000  0.000734  0.000000  0.000000  0.001976  0.000000   
...       ...       ...       ...       ...       ...       ...       ...   
9995  0.00000  0.006250  0.000000  0.000000  0.000000  0.006472  0.000013   
9996  0.00000  0.008572  0.000000  0.012587  0.006617  0.062284  0.000000   
9997  0.00000  0.000000  0.015776  0.000000  0.186676  0.000000  0.000000   
9998  0.00000  0.002482  0.001582  0.003299  0.003598  0.050464  0.000000   
9999  0.00000  0.000000  0.000000  0.095252  0.000000  0.000000  0.000000   

      topic_14  
0     0.043641  
1     0.000000  
2     0.027147  
3     0.035090  
4     0.014186  
...        ...  
9995  0.029493  
9996  0.046621  
9997  0.023513  
9998  0.039599  
9999  0.019916  

[10000 rows x 15 columns]

In [36]:
#prendre le coef max pour chaque review lié à un topic
liste=[]
for i in df_topic.columns:
  data_f=df_topic.sort_values(by=i, ascending=False)
  liste.append(data_f.index[:2].to_list())
print(liste)

[[1510, 3111], [9916, 920], [5484, 6518], [6369, 4146], [375, 1698], [9601, 6166], [6270, 7346], [4098, 1032], [9130, 1114], [5669, 9897], [1691, 7240], [4682, 5222], [6384, 7258], [6286, 9041], [9098, 6568]]


In [41]:
df_6=pandas.DataFrame(doc_topic)
dict={}
for i in range(15):
  top_2=df_6.nlargest(2,i,keep='all')
  top2_indexes=top_2[0].keys().to_list()
  dict[i]=df['text'][top2_indexes].to_list()
df_corr=pandas.DataFrame(dict)
df_corr
#print(dict.get(5))

0   \
0  I called due to a ad on a website provided by ...   
1  I never leave bad reviews but this one is post...   

                                                  1   \
0  There's some really strange decor inside, like...   
1  This place used to be a cool, chill place. Now...   

                                                  2   \
0  Ok we tried Mod pizza tonight for 1st time. We...   
1  I ordered pizza by the phone call. When I got ...   

                                                  3   \
0  Great prices but I think that they are quantit...   
1  Don't bother pre-ordering online.  They don't ...   

                                                  4   \
0  the food cannot be catogorized as asian food. ...   
1  bad service dont go here! They needs to learn ...   

                                                  5   \
0  Unos is actually my favorite restaurant and ye...   
1  If you can get take out, I highly recommend it...   

                                                  6   \
0  The service was good but they forgot several i...   
1  Really rather disappointing, got a burger and ...   

                                                  7   \
0  Seriously it's worth the wait!? We waited frea...   
1  An hour and a half of waiting, and still NO FO...   

                                                  8   \
0  This chicken is not all that. It's just lightl...   
1  Two recent visits and I have to ask...where's ...   

                                                  9   \
0  Roscoe's is your middle-of-the-road bar locate...   
1  We went here on a Saturday night when they had...   

                                                  10  \
0  Second time I got food poisoning from this pla...   
1  We have been to Roscoe's several times over th...   

                                                  11  \
0  We went there for Taco Tuesday tonight . Not w...   
1  I initially came here thinking it was a differ...   

                                                  12  \
0  I'm a sandwich guy. I live for a good sandwich...   
1  Stopped here today for lunch after having read...   

                                                  13  \
0  I go to an AYCE sushi for the pure goal of sat...   
1  There seems to be a hole in decent sushi in st...   

                                                  14  
0  I love Greek food and have eaten at many Greek...  
1  $40 for dinner for two for Vietnamese, no booz...

#Interpretation de Topic

In [38]:
interpretation_topi={
    'topic0' : 'TICKET PAYEMENT',
    'topic1' : 'OVERLOADED RESTAURANT',
    'topic2' : 'PIZZA/DELIVERY',
    'topic3' : 'PRICES/ONLINE-ORDERING',
    'topic4' : 'FOOD/SERVICE',
    'topic5' : 'TABLE/BOTHERING',
    'topic6' : 'SERVICE',
    'topic7' : 'TEMPS D ATTENTE',
    'topic8' : 'CHICKEN',
    'topic9' : 'BEER/BAR',
    'topic10' : 'BAD PLACE TO EAT',
    'topic11' : 'SUSHI',
    'topic12' : 'LUNCH/SANDWICH',
    'topic13' : 'AMBIANCE',
    'topic14' : 'WAITER'
}

Fichier Pickle Vectoriseur

In [39]:
import pickle
with open('vectorizer.bin', 'wb') as fichier:
  pickle.dump(X, fichier, pickle.HIGHEST_PROTOCOL)

Fichier Pickle Modèle

In [40]:
import pickle
with open('model_nmf.bin', 'wb') as fichier:
  pickle.dump(nmf_model, fichier, pickle.HIGHEST_PROTOCOL)
